2022-08-18 15:01:54,875 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Configure stats pid to 2528
2022-08-18 15:01:54,875 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2022-08-18 15:01:54,875 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Loading settings from c:\Users\user\OneDrive\문서\NLP\base_line_transformer\wandb\settings
2022-08-18 15:01:54,875 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True', 'mode': 'online'}
2022-08-18 15:01:54,875 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-08-18 15:01:54,876 INFO    MainThread:2528 [wandb_init.py:_log_setup():461] Logging user logs to c:\Users\user\OneDrive\문서\NLP\base_line_transformer\wandb\run-20220818_150154-3sqwzovu\logs\debug.log
2022-08-18 15:01:54,876 INFO    MainThread:2528 [wandb_init.py:_log_setup():462] Logging internal logs to c:\Users\user\OneDrive\문서\NLP\base_line_transformer\wandb\run-20220818_150154-3sqwzovu\logs\debug-internal.log
2022-08-18 15:01:54,876 INFO    MainThread:2528 [wandb_init.py:_jupyter_setup():411] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002A0BEE45BB0>
2022-08-18 15:01:54,876 INFO    MainThread:2528 [wandb_init.py:init():495] calling init triggers
2022-08-18 15:01:54,876 INFO    MainThread:2528 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {'VOCAB_SIZE': 10000, 'SEQ_LEN': 60, 'N': 2, 'HIDDEN_DIM': 256, 'NUM_HEAD': 8, 'INNER_DIM': 512, 'BATCH_SIZE': 64, 'WEIGHT_DECAY': 0, 'LEARNING_RATE': 0.0001}
2022-08-18 15:01:54,876 INFO    MainThread:2528 [wandb_init.py:init():548] starting backend
2022-08-18 15:01:54,876 INFO    MainThread:2528 [wandb_init.py:init():552] setting up manager
2022-08-18 15:01:54,881 INFO    MainThread:2528 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-08-18 15:01:54,887 INFO    MainThread:2528 [wandb_init.py:init():558] backend started and connected
2022-08-18 15:01:54,891 INFO    MainThread:2528 [wandb_run.py:_label_probe_notebook():1105] probe notebook
2022-08-18 15:01:54,892 INFO    MainThread:2528 [wandb_run.py:_label_probe_notebook():1115] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-08-18 15:01:54,892 INFO    MainThread:2528 [wandb_init.py:init():636] updated telemetry
2022-08-18 15:01:54,900 INFO    MainThread:2528 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-08-18 15:01:57,945 WARNING MsgRouterThr:2528 [router.py:message_loop():76] message_loop has been closed
2022-08-18 15:02:24,910 INFO    MainThread:2528 [interface_shared.py:_communicate_run():331] couldn't get run from backend
2022-08-18 15:02:24,910 ERROR   MainThread:2528 [wandb_init.py:init():676] backend process timed out
2022-08-18 15:02:24,910 ERROR   MainThread:2528 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-08-18 15:08:22,816 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Configure stats pid to 2528
2022-08-18 15:08:22,816 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2022-08-18 15:08:22,816 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Loading settings from c:\Users\user\OneDrive\문서\NLP\base_line_transformer\wandb\settings
2022-08-18 15:08:22,816 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True', 'mode': 'online'}
2022-08-18 15:08:22,817 INFO    MainThread:2528 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-08-18 15:08:22,817 INFO    MainThread:2528 [wandb_init.py:_log_setup():461] Logging user logs to c:\Users\user\OneDrive\문서\NLP\base_line_transformer\wandb\run-20220818_150822-ofwjiv4u\logs\debug.log
2022-08-18 15:08:22,817 INFO    MainThread:2528 [wandb_init.py:_log_setup():462] Logging internal logs to c:\Users\user\OneDrive\문서\NLP\base_line_transformer\wandb\run-20220818_150822-ofwjiv4u\logs\debug-internal.log
2022-08-18 15:08:22,817 INFO    MainThread:2528 [wandb_init.py:init():495] calling init triggers
2022-08-18 15:08:22,817 INFO    MainThread:2528 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {'VOCAB_SIZE': 10000, 'SEQ_LEN': 60, 'N': 2, 'HIDDEN_DIM': 256, 'NUM_HEAD': 8, 'INNER_DIM': 512, 'BATCH_SIZE': 64, 'WEIGHT_DECAY': 0, 'LEARNING_RATE': 0.0001}
2022-08-18 15:08:22,817 INFO    MainThread:2528 [wandb_init.py:init():548] starting backend
2022-08-18 15:08:22,817 INFO    MainThread:2528 [wandb_init.py:init():552] setting up manager
2022-08-18 15:08:22,838 ERROR   MainThread:2528 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "c:\Users\user\anaconda3\envs\for_wdb\lib\site-packages\wandb\sdk\wandb_init.py", line 1043, in init
    run = wi.init()
  File "c:\Users\user\anaconda3\envs\for_wdb\lib\site-packages\wandb\sdk\wandb_init.py", line 553, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "c:\Users\user\anaconda3\envs\for_wdb\lib\site-packages\wandb\sdk\wandb_manager.py", line 161, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "c:\Users\user\anaconda3\envs\for_wdb\lib\site-packages\wandb\sdk\service\service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "c:\Users\user\anaconda3\envs\for_wdb\lib\site-packages\wandb\sdk\lib\sock_client.py", line 140, in send
    self.send_server_request(server_req)
  File "c:\Users\user\anaconda3\envs\for_wdb\lib\site-packages\wandb\sdk\lib\sock_client.py", line 84, in send_server_request
    self._send_message(msg)
  File "c:\Users\user\anaconda3\envs\for_wdb\lib\site-packages\wandb\sdk\lib\sock_client.py", line 81, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\user\anaconda3\envs\for_wdb\lib\site-packages\wandb\sdk\lib\sock_client.py", line 61, in _sendall_with_error_handle
    sent = self._sock.send(data[total_sent:])
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다
